package com.loomlink.edge.domain.enums;

/**
 * Lifecycle states for a robot inspection mission.
 * Compatible with Flotilla mission status model.
 */
public enum MissionStatus {

    PLANNING("Mission being generated by AI planner"),
    READY("Mission approved and ready for dispatch"),
    DISPATCHED("Mission sent to robot via ISAR"),
    IN_PROGRESS("Robot actively executing mission"),
    PAUSED("Mission paused — awaiting operator decision"),
    COMPLETED("Mission completed successfully"),
    ABORTED("Mission aborted by operator or safety system"),
    FAILED("Mission failed — robot error or connectivity loss");

    private final String description;

    MissionStatus(String description) {
        this.description = description;
    }

    public String getDescription() { return description; }

    public boolean isTerminal() {
        return this == COMPLETED || this == ABORTED || this == FAILED;
    }

    public boolean isActive() {
        return this == IN_PROGRESS || this == DISPATCHED;
    }
}
